### ISSUE TITLE
Configuration Home Assistant échoué

### ISSUE THREAD

**Issue by Lens40** [fairecasoimeme/ZiPulses#15]
J'ai pu appairer le zipulse avec la clé USB sonoff qui est aussi connecté avec Lixee (qui marche parfaitement) mais sur la configuration cela échoue. J'ai un binding et le reporting affiché en vert mais pour le reste j'ai que des croix orange. 

Donc je peux voir le zipulse dans Home Assistant mais je n'ai aucune entité.

**Comment by fairecasoimeme** [comment]
Si la demande de configuration est effectuée en dehors du processus d'appairage, il faut actionner le bouton du ZiPulses pour le réveiller. Si vous n'avez aucune entité, je pense qu'il faut refaire la procédure d'appairage.

**Comment by Lens40** [comment]
Merci, le zipulse clignote en continue mais après plusieurs minutes (5min et plus) il n‘est toujours pas configuré après un nouveau appairage. Aussi le lancement d’une nouvelle configuration a échoué.

**Comment by fairecasoimeme** [comment]
Si le zipulses clignote, c'est qu'il n'arrive pas à s'appairer. Du coup, il y a un problème de portée. Soit distance, soit perturbation.
Pour vérifier qu'il fonctionne correctement, il faut commencer par le rapprocher du coordinateur. Si l'appairage se fait correctement, il faut "analyser" le réseau pour régler le problème de distance ou perturbation

**Comment by Lens40** [comment]
Merci. Les deux sont à 10 cm. Donc pas de problème à ce niveau la. L‘appairage fonctionne, il est bien reconnu mais il ne fait pas la configuration. Le RSSI est à -3 et le LQI a 255.

**Comment by fairecasoimeme** [comment]
Vous utilisez ZHA ou Z2M avec quelle version ?
Pouvez-vous faire une capture d'écran ?

**Comment by Lens40** [comment]
Merci pour votre temps. J‘utilise ZHA. Et j‘ai la dernière version de Home Assistant
![IMG_9070](https://github.com/fairecasoimeme/ZiPulses/assets/19168364/90b9dcb4-0750-4962-b564-61396e17dd12)
![IMG_9072](https://github.com/fairecasoimeme/ZiPulses/assets/19168364/32ddb8bc-0507-43f0-a165-bbcff3c26b75)
![IMG_9071](https://github.com/fairecasoimeme/ZiPulses/assets/19168364/a751a2b4-d0d0-41fb-92dc-f72669f120b9)

**Comment by Lens40** [comment]
Il y a du nouveau? Comment puis-je le faire fonctionner?

**Comment by fairecasoimeme** [comment]
Désolé mais les captures d'écrans n'apportent rien. vous devez "slider" vers le bas pour voir les capteurs

**Comment by Mika59940** [comment]
Bonjour, en appairant le zipulses j'arrive à configuer le multiplicator et le divisor par contre impossible à modifier l'unité de mesure ,  je n'ai pas la tension de la pile et température. Voici ce que j'ai trouvé dans le journal de Zigbee2MQTT:



`2023-10-05 08:05:43Failed to configure '0x00158d0005ce760f', attempt 1 (Error: Read 0x00158d0005ce760f/1 seMetering(["divisor","unitOfMeasure","multiplier"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":25784,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')) at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32))`

**Comment by fairecasoimeme** [comment]
Bonjour, la valeur modifiée doit être un entier en respectant le tableau des unité de mesures : https://github.com/fairecasoimeme/ZiPulses#tableau-dunit%C3%A9-de-mesure

**Comment by fairecasoimeme** [comment]
Bonjour,
Il est normal de ne pas avoir de rapport.
Pour l'unité de mesure, avez-vous suivi le tutoriel ?
https://github.com/fairecasoimeme/ZiPulses#z2m

**Comment by Mika59940** [comment]
Bonjour  @fairecasoimeme , j'ai bien suivi le tuto car 'Multiplier' et 'divisor' se modifient  sans problème . Seulement 'UnitOfMeasure' que je n'arrive pas à modifié .

Info sur les versions:

- ZiPulses: 4000 0004

- Zigbee2MQTT: 1.33.1-1

**Comment by tomj44300** [comment]
Bonjour @fairecasoimeme je viens de recevoir mon zipulses ce midi avec la fw 4000 0006 et utilise Z2M 1.33.2 , j'ai exactement le même problème que @Mika59940 pour configurer en L avec mon compteur d'eau Diehl izar pulse I
As tu depuis trouver une solution ?
Et oui j'ai bien suivi le tuto et comme Mika je peut changer multiplier et divisor
Merci pour ton aide

**Comment by fairecasoimeme** [comment]
https://github.com/fairecasoimeme/ZiPulses/issues/21#issuecomment-1788820015

**Comment by rs** [comment]
Je rencontre un problème similaire à @Lens40. Lors de l'ajout dans home assistant via ZHA, la phase de configuration ne termine jamais et le device est ajouté de façon incomplète à home assistant. Seul la température est disponible et j'obtiens des erreurs de ce type dans les logs :

```
2023-12-28 15:08:28.457 INFO (MainThread) [zigpy.endpoint] [0x3676:1] Discovered endpoint information: SizePrefixedSimpleDescriptor(endpoint=1, profile=260, dev
ice_type=263, device_version=1, input_clusters=[0, 1, 3, 1026, 1794], output_clusters=[4, 3, 1794])
2023-12-28 15:08:28.459 DEBUG (MainThread) [zigpy.zcl] [0x3676:1:0x0000] Sending request header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GLOB
AL_COMMAND: 0>, is_manufacturer_specific=False, direction=<Direction.Server_to_Client: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_genera
l=True), tsn=94, command_id=<GeneralCommand.Read_Attributes: 0>, *direction=<Direction.Server_to_Client: 0>)
2023-12-28 15:08:28.460 DEBUG (MainThread) [zigpy.zcl] [0x3676:1:0x0000] Sending request: Read_Attributes(attribute_ids=[4, 5])
2023-12-28 15:08:28.462 DEBUG (MainThread) [zigpy.device] [0x3676] Extending timeout for 0x5e request
2023-12-28 15:08:28.463 DEBUG (MainThread) [bellows.zigbee.application] Sending packet ZigbeePacket(timestamp=datetime.datetime(2023, 12, 28, 14, 8, 28, 463113,
 tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, add
ress=0x3676), dst_ep=1, source_route=None, extended_timeout=True, tsn=94, profile_id=260, cluster_id=0, data=Serialized[b'\x00^\x00\x04\x00\x05\x00'], tx_option
s=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2023-12-28 15:08:28.464 DEBUG (MainThread) [bellows.ezsp.protocol] Send command setExtendedTimeout: (00:15:8d:00:05:d2:5e:4f, True)
2023-12-28 15:08:28.466 DEBUG (MainThread) [bellows.uart] Sending: b'570e21a92a2a5aec8b914aa8bf559342497e'
2023-12-28 15:08:28.472 DEBUG (MainThread) [bellows.uart] Data frame: b'760ea1a92a2ada0f7e'
2023-12-28 15:08:28.472 DEBUG (MainThread) [bellows.uart] Sending: b'8070787e'
2023-12-28 15:08:28.472 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received setExtendedTimeout: []
2023-12-28 15:08:28.473 DEBUG (MainThread) [bellows.ezsp.protocol] Send command sendUnicast: (<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 0x3676, EmberApsFra
me(profileId=260, clusterId=0, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_RETRY|APS_OPTION_ENABLE_ROUTE_DISCOVERY: 320>, groupI
d=0, sequence=94), 95, b'\x00^\x00\x04\x00\x05\x00')
2023-12-28 15:08:28.474 DEBUG (MainThread) [bellows.uart] Sending: b'600f21a9602a15c46f904b25aa5493099d4e27f5b2c967d5fdc2638cfcd03f7e'
2023-12-28 15:08:28.485 DEBUG (MainThread) [bellows.uart] Data frame: b'070fa1a9602a15c607867e'
2023-12-28 15:08:28.485 DEBUG (MainThread) [bellows.uart] Sending: b'8160597e'
2023-12-28 15:08:28.485 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received sendUnicast: [<EmberStatus.SUCCESS: 0>, 116]
2023-12-28 15:08:28.528 DEBUG (MainThread) [bellows.uart] Data frame: b'170fb1a96b2a15c46f904b25aa5493099d4e27dfb2ce677b6c7e'
2023-12-28 15:08:28.528 DEBUG (MainThread) [bellows.uart] Sending: b'82503a7e'
2023-12-28 15:08:28.530 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received messageSentHandler: [<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>
, 13942, EmberApsFrame(profileId=260, clusterId=0, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_RETRY|APS_OPTION_ENABLE_ROUTE_DIS
COVERY: 320>, groupId=0, sequence=116), 95, <EmberStatus.SUCCESS: 0>, b'']
2023-12-28 15:08:28.530 DEBUG (MainThread) [bellows.zigbee.application] Received messageSentHandler frame with [<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 1
3942, EmberApsFrame(profileId=260, clusterId=0, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_RETRY|APS_OPTION_ENABLE_ROUTE_DISCOV
ERY: 320>, groupId=0, sequence=116), 95, <EmberStatus.SUCCESS: 0>, b'']
2023-12-28 15:08:28.548 DEBUG (MainThread) [bellows.uart] Data frame: b'270fb1a9112a15b658944a24ab5593499c80ab149bf89874e7de3d88f87e3fe5ee81b737ea9ac2dbd59061d6
2f73dc80055ed6cb4a7e'
2023-12-28 15:08:28.549 DEBUG (MainThread) [bellows.uart] Sending: b'83401b7e'
2023-12-28 15:08:28.552 DEBUG (MainThread) [bellows.ezsp.protocol] Application frame received incomingMessageHandler: [<EmberIncomingMessageType.INCOMING_UNICAS
T: 0>, EmberApsFrame(profileId=260, clusterId=0, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY: 256>, group
Id=0, sequence=206), 140, -65, 0x3676, 255, 255, b'\x18^\x01\x04\x00\x00B\x05LiXee\x05\x00\x00B\x08ZiPulses']
2023-12-28 15:08:28.553 DEBUG (MainThread) [bellows.zigbee.application] Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST:
0>, EmberApsFrame(profileId=260, clusterId=0, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY: 256>, groupId=
0, sequence=206), 140, -65, 0x3676, 255, 255, b'\x18^\x01\x04\x00\x00B\x05LiXee\x05\x00\x00B\x08ZiPulses']
2023-12-28 15:08:28.554 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2023, 12, 28, 14, 8, 28, 554327, tzin
fo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x3676), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=
0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=206, profile_id=260, cluster_id=0, data=Serialized[b'\x18^\x01\x04\x00\x00B\x05LiXee\x05\x00\x
00B\x08ZiPulses'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=140, rssi=-65)
2023-12-28 15:08:28.557 DEBUG (MainThread) [zigpy.zcl] [0x3676:1:0x0000] Received ZCL frame: b'\x18^\x01\x04\x00\x00B\x05LiXee\x05\x00\x00B\x08ZiPulses'
2023-12-28 15:08:28.558 DEBUG (MainThread) [zigpy.zcl] [0x3676:1:0x0000] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.GL
OBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Client_to_Server: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=
True), tsn=94, command_id=1, *direction=<Direction.Client_to_Server: 1>)
2023-12-28 15:08:28.561 DEBUG (MainThread) [zigpy.zcl] [0x3676:1:0x0000] Decoded ZCL frame: Basic:Read_Attributes_rsp(status_records=[ReadAttributeRecord(attrid
=0x0004, status=<Status.SUCCESS: 0>, value=TypeValue(type=CharacterString, value='LiXee')), ReadAttributeRecord(attrid=0x0005, status=<Status.SUCCESS: 0>, value
=TypeValue(type=CharacterString, value='ZiPulses'))])
2023-12-28 15:08:28.563 INFO (MainThread) [zigpy.device] [0x3676] Read model 'ZiPulses' and manufacturer 'LiXee' from <Endpoint id=1 in=[basic:0x0000, power:0x0
001, identify:0x0003, temperature:0x0402, smartenergy_metering:0x0702] out=[groups:0x0004, identify:0x0003, smartenergy_metering:0x0702] status=<Status.ZDO_INIT
: 1>>
2023-12-28 15:08:28.564 INFO (MainThread) [zigpy.device] [0x3676] Discovered basic device information for <Device model='ZiPulses' manuf='LiXee' nwk=0x3676 ieee
=00:15:8d:00:05:d2:5e:4f is_initialized=True>
2023-12-28 15:08:28.564 DEBUG (MainThread) [zigpy.application] Device is initialized <Device model='ZiPulses' manuf='LiXee' nwk=0x3676 ieee=00:15:8d:00:05:d2:5e
:4f is_initialized=True>
2023-12-28 15:08:28.570 DEBUG (MainThread) [zigpy.quirks.registry] Checking quirks for LiXee ZiPulses (00:15:8d:00:05:d2:5e:4f)
2023-12-28 15:08:28.570 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'AqaraH1.RemoteH1DoubleRocker5'>
2023-12-28 15:08:28.570 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {1, 2, 3} {1}
2023-12-28 15:08:28.570 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'AqaraH1.RemoteH1DoubleRocker5'>
2023-12-28 15:08:28.571 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {1, 2, 3} {1}
2023-12-28 15:08:28.571 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'AqaraH1.RemoteH1DoubleRocker5'>
2023-12-28 15:08:28.571 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {1, 2, 3} {1}
2023-12-28 15:08:28.571 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'AqaraH1.RemoteH1DoubleRocker5'>
2023-12-28 15:08:28.571 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {1, 2, 3} {1}
2023-12-28 15:08:28.571 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'AqaraH1.RemoteH1DoubleRocker5'>
2023-12-28 15:08:28.571 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {1, 2, 3} {1}
2023-12-28 15:08:28.572 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.xbee.xbee_io.XBeeSensor'>
2023-12-28 15:08:28.572 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {232, 230} {1}
2023-12-28 15:08:28.572 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.xbee.xbee3_io.XBee3Sensor'>
2023-12-28 15:08:28.572 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {232, 230} {1}
2023-12-28 15:08:28.572 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.tuya.ts0201.MoesTemperatureHumidtySensorWithScreen'>
2023-12-28 15:08:28.573 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2023-12-28 15:08:28.573 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.smartthings.tag_v4.SmartThingsTagV4'>
2023-12-28 15:08:28.573 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2023-12-28 15:08:28.573 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.smartthings.multi.SmartthingsMultiPurposeSensor'>
2023-12-28 15:08:28.573 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2023-12-28 15:08:28.573 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.netvox.z308e3ed.Z308E3ED'>
2023-12-28 15:08:28.573 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2023-12-28 15:08:28.574 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.gledopto.soposhgu10.SoposhGU10'>
2023-12-28 15:08:28.574 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {11, 13} {1}
2023-12-28 15:08:28.578 INFO (MainThread) [homeassistant.components.zha.core.endpoint] Creating cluster handler for cluster id: 0 class: <class 'homeassistant.c
omponents.zha.core.cluster_handlers.general.BasicClusterHandler'>
2023-12-28 15:08:28.579 INFO (MainThread) [homeassistant.components.zha.core.endpoint] Creating cluster handler for cluster id: 1 class: <class 'homeassistant.c
omponents.zha.core.cluster_handlers.general.PowerConfigurationClusterHandler'>
2023-12-28 15:08:28.580 INFO (MainThread) [homeassistant.components.zha.core.endpoint] Creating cluster handler for cluster id: 3 class: <class 'homeassistant.c
omponents.zha.core.cluster_handlers.general.Identify'>
2023-12-28 15:08:28.580 INFO (MainThread) [homeassistant.components.zha.core.endpoint] Creating cluster handler for cluster id: 1026 class: <class 'homeassistan
t.components.zha.core.cluster_handlers.measurement.TemperatureMeasurement'>
2023-12-28 15:08:28.581 INFO (MainThread) [homeassistant.components.zha.core.endpoint] Creating cluster handler for cluster id: 1794 class: <class 'homeassistan
t.components.zha.core.cluster_handlers.smartenergy.Metering'>
2023-12-28 15:08:28.582 DEBUG (MainThread) [homeassistant.components.zha.core.discovery] Discovering entities for endpoint: 00:15:8d:00:05:d2:5e:4f-1
2023-12-28 15:08:28.586 DEBUG (MainThread) [homeassistant.components.zha.core.discovery] 'button' component -> 'ZHAIdentifyButton' using ['identify']
2023-12-28 15:08:28.587 DEBUG (MainThread) [homeassistant.components.zha.core.discovery] 'sensor' component -> 'Battery' using ['power']
2023-12-28 15:08:28.587 DEBUG (MainThread) [homeassistant.components.zha.core.discovery] 'sensor' component -> 'Temperature' using ['temperature']
2023-12-28 15:08:28.587 DEBUG (MainThread) [homeassistant.components.zha.core.discovery] 'sensor' component -> 'RSSISensor' using ['basic']
2023-12-28 15:08:28.587 DEBUG (MainThread) [homeassistant.components.zha.core.discovery] 'sensor' component -> 'LQISensor' using ['basic']
2023-12-28 15:08:28.587 DEBUG (MainThread) [homeassistant.components.zha.core.discovery] 'sensor' component -> 'SmartEnergyMetering' using ['smartenergy_meterin
g']
2023-12-28 15:08:28.587 DEBUG (MainThread) [homeassistant.components.zha.core.discovery] 'sensor' component -> 'SmartEnergySummation' using ['smartenergy_meteri
ng']
2023-12-28 15:08:28.594 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] device - 0x3676:00:15:8d:00:05:d2:5e:4f entering async_device_initialized
 - is_new_join: True
2023-12-28 15:08:28.595 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] device - 0x3676:00:15:8d:00:05:d2:5e:4f has joined the ZHA zigbee network

2023-12-28 15:08:28.596 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x3676](ZiPulses): started configuration
2023-12-28 15:08:28.596 DEBUG (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3676:ZDO](ZiPulses): 'async_configure' stage succeeded
2023-12-28 15:08:28.605 DEBUG (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3676:1:0x0702]: Performing cluster binding
2023-12-28 15:08:28.606 DEBUG (MainThread) [zigpy.device] [0x3676] Extending timeout for 0x60 request
2023-12-28 15:08:28.606 DEBUG (MainThread) [bellows.zigbee.application] Sending packet ZigbeePacket(timestamp=datetime.datetime(2023, 12, 28, 14, 8, 28, 606914,
 tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, add
ress=0x3676), dst_ep=0, source_route=None, extended_timeout=True, tsn=96, profile_id=0, cluster_id=<ZDOCmd.Bind_req: 0x0021>, data=Serialized[b'`O^\xd2\x05\x00\
x8d\x15\x00\x01\x02\x07\x03\x1b!\x06\xff\xff.!\x00\x01'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2023-12-28 15:08:28.607 DEBUG (MainThread) [bellows.ezsp.protocol] Send command setExtendedTimeout: (00:15:8d:00:05:d2:5e:4f, True)
2023-12-28 15:08:28.608 DEBUG (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3676:1:0x0402]: Performing cluster binding
2023-12-28 15:08:28.609 DEBUG (MainThread) [zigpy.device] [0x3676] Extending timeout for 0x62 request
2023-12-28 15:08:28.609 DEBUG (MainThread) [bellows.zigbee.application] Sending packet ZigbeePacket(timestamp=datetime.datetime(2023, 12, 28, 14, 8, 28, 609365,
 tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, add
ress=0x3676), dst_ep=0, source_route=None, extended_timeout=True, tsn=98, profile_id=0, cluster_id=<ZDOCmd.Bind_req: 0x0021>, data=Serialized[b'bO^\xd2\x05\x00\
x8d\x15\x00\x01\x02\x04\x03\x1b!\x06\xff\xff.!\x00\x01'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2023-12-28 15:08:28.610 DEBUG (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3676:1:0x0001]: Performing cluster binding
2023-12-28 15:08:28.612 DEBUG (MainThread) [zigpy.device] [0x3676] Extending timeout for 0x64 request
2023-12-28 15:08:28.613 DEBUG (MainThread) [bellows.zigbee.application] Sending packet ZigbeePacket(timestamp=datetime.datetime(2023, 12, 28, 14, 8, 28, 613084,
 tzinfo=datetime.timezone.utc), src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), src_ep=0, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, add
ress=0x3676), dst_ep=0, source_route=None, extended_timeout=True, tsn=100, profile_id=0, cluster_id=<ZDOCmd.Bind_req: 0x0021>, data=Serialized[b'dO^\xd2\x05\x00
\x8d\x15\x00\x01\x01\x00\x03\x1b!\x06\xff\xff.!\x00\x01'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=None, rssi=None)
2023-12-28 15:08:28.614 DEBUG (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3676:1:0x0003]: Configuring cluster attribute reporting
2023-12-28 15:08:28.614 DEBUG (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3676:1:0x0003]: finished cluster handler configuration
2023-12-28 15:08:28.614 DEBUG (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3676:1:0x0000]: Configuring cluster attribute reporting
2023-12-28 15:08:28.615 DEBUG (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x3676:1:0x0000]: finished cluster handler configuration
2023-12-28 15:08:28.616 DEBUG (MainThread) [bellows.uart] Sending: b'730c21a92a2a5aec8b914aa8bf5593b22d7e'
2023-12-28 15:08:28.617 DEBUG (MainThread) [zigpy.appdb] Error handling '_save_attribute' event with (00:15:8d:00:05:d2:5e:4f, 1, 0, 4, 'LiXee', datetime.dateti
me(2023, 12, 28, 14, 8, 28, 563343, tzinfo=datetime.timezone.utc)) params: FOREIGN KEY constraint failed
2023-12-28 15:08:28.621 DEBUG (MainThread) [zigpy.appdb] Error handling '_save_attribute' event with (00:15:8d:00:05:d2:5e:4f, 1, 0, 5, 'ZiPulses', datetime.dat
etime(2023, 12, 28, 14, 8, 28, 563446, tzinfo=datetime.timezone.utc)) params: FOREIGN KEY constraint failed
…
```

Il y a d'avantage de logs dispo si besoin.

**Comment by fairecasoimeme** [comment]
Bonjour,
Il faut simplement appuyer régulièrement sur le bouton "Link" du ZiPulses lors de l'appairage pour le réveiller. Sinon refaire la procédure d'appairage.

**Comment by rs** [comment]
Le réveiller permet effectivement d'arriver au bout de l'appairage, mais ensuite les valeurs reste "unavailable" malgré plusieurs pulses de test: 
<img width="662" alt="image" src="https://github.com/fairecasoimeme/ZiPulses/assets/68232/1257c9ea-24d8-4516-980b-034af7365e7f">

**Comment by fairecasoimeme** [comment]
Quel est le LQI de l'appareil ?

**Comment by rs** [comment]
LQI: 120
RSSI: -70

**Comment by fairecasoimeme** [comment]
Pour tester, pouvez-vous refaire l'appairage à côté du coordinateur zigbee ?

**Comment by rs** [comment]
Cela fonctionne mieux effectivement. Je l'ai ensuite branché au gazpar, mais il ne semble enregistrer aucune pulsation. L'entity `sensor.lixee_zipulses_summation_delivered` reste invariablement à 0. Le sensor de température lui semble fonctionner.

**Comment by fairecasoimeme** [comment]
Attention, il y a aussi un sens dans le branchement au Gazpar
https://github.com/fairecasoimeme/ZiPulses#compteur-gazpar
